### ISSUE TITLE
Autoplay

### ISSUE THREAD

**Issue by ninacoder** [CodyHouse/horizontal-timeline#1]
Ciao claudia,
intanto complimenti per il lavoro. Mi chiedevo se fosse possibile rendere la timeline automatica con una sorta di autoplay.. in modo da farla scorrere da sola senza il click dell'utente.

**Comment by claudia-romano** [comment]
Ciao Nicoletta,
scusa il ritardo.

L'autoplay è un'opzione che non pianifichiamo di implementare. Ma puoi usare la function keyNavigateTimeline definita nel file main.js, facendola girare ad intervalli regolari con un setTimeout.

Cheers!

**Comment by chrisdoman** [comment]
It took me a while to get this working, so in case it is useful for other people - this is how I got autoplay to work:



        function daydiff(first, second) { // time distance between events
            return Math.round((second-first));
        };

    window.HorizontalTimeline = HorizontalTimeline;

    keep_playing = false;

    function play_click() {

            if (! keep_playing) {
            keep_playing = true;
            play_loop();
            $("#play-button").html('<i class="fa fa-pause"></i>');
            } else {
            keep_playing = false;
            $("#play-button").html('<i class="fa fa-play"></i>');
            }
            
        }


        function play_loop() {
            if (keep_playing) {
            // next_click();
            updateHorizontalTimeline('next');
        
            setTimeout(play_loop, 3000);
        }
        }

    var horizontalTimeline = document.getElementsByClassName('js-cd-h-timeline'),
        horizontalTimelineTimelineArray = [];
    if(horizontalTimeline.length > 0) {
            for(var i = 0; i < horizontalTimeline.length; i++) {
                horizontalTimelineTimelineArray.push(new HorizontalTimeline(horizontalTimeline[i])); 
            }
            // navigate the timeline when inside the viewport using the keyboard
            document.addEventListener('keydown', function(event){
                if( (event.keyCode && event.keyCode == 39) || ( event.key && event.key.toLowerCase() == 'arrowright') ) {
                    updateHorizontalTimeline('next'); // move to next event
                } else if((event.keyCode && event.keyCode == 37) || ( event.key && event.key.toLowerCase() == 'arrowleft')) {
                    updateHorizontalTimeline('prev'); // move to prev event
                }
            });

            document.getElementById("play-button").addEventListener("click", function(){
                play_click();
            });
    };

**Comment by sebastiano-guerriero** [comment]
@chrisdoman thanks for sharing!
