### ISSUE TITLE
Multiple Timelines on same page!

### ISSUE THREAD

**Issue by AdnanBoota** [CodyHouse/horizontal-timeline#10]
Hi,

Thanks for the great plugin!

I'm trying to use multiple timelines on the same page, but there is some problem in doing that, it doesn't add "selected" class to the 'a' links in the 2nd timeline and thus breaks.

Could you please help me or tell me how to figure it out?

Regards,
Adnan
![timeline_issues](https://user-images.githubusercontent.com/14972616/45164662-3b02ab00-b1f3-11e8-936f-4b82cbafda1a.png)

**Comment by claudia-romano** [comment]
Hi there, sorry for getting back after quite some time.
We have just released a new version (2.0) of this experiment (based on the [CodyHouse framework](https://codyhouse.co/ds/docs/framework)) that fixes this issue.
