### ISSUE TITLE
timeline disappeared without dots and lines

### ISSUE THREAD

**Issue by astro813** [CodyHouse/horizontal-timeline#13]
Hi, I am new for here, In my case, I google that this issue and found this [article](https://stackoverflow.com/questions/29894338/horizontal-timeline-missing-dots). but I fresh for CSS, don't know how to change this at the .scss file in your project. TX

**Comment by sebastiano-guerriero** [comment]
Hi there! I'm afraid you're not providing enough info about the issue. There can be many reasons why something is not working as expected when merged into your custom CSS. Btw the timeline linked in your comment is not the one available on CodyHouse. 

I'm going to close this issue for lack of info. Feel free to open another issue if you can, for example,  recreate the bug in a pen on Codepen so we can look at the code.

**Comment by astro813** [comment]
Hi, there, sorry for the insufficient explanation, Here is my [code.](https://codepen.io/astro813/pen/pBKvKb).  
I just wanna create the tabs, which every tab(which called One and Two) contain one horizontal timeline. (Don't know how to include Jquery and timeline library at codepen. so please include it's at your local computer to make it work.). TX.

**Comment by astro813** [comment]
Hi, just fond that the dots not disappeared, there are overlapped at one. Hope this could useful for your understanding.

**Comment by sebastiano-guerriero** [comment]
Sorry but I meant we can check and see if there are issues if you can recreate them using only our code. It's impossible for us to go through cases where our code is intertwined with custom code. By taking a quick look at your pen, I can see the CSS is not being loaded.
