### ISSUE TITLE
Problem Iterating events with angular

### ISSUE THREAD

**Issue by luisjf** [CodyHouse/horizontal-timeline#2]
Hello! I'm trying to iterate my event list with angular ng-repeat but when the timeline is load all events end at the same point, I feel it is that data arrives after the timeline.js runs, anyone knows this issue?

**Comment by HotEvent** [comment]
look this demo https://github.com/BlackBoys/angular-horizontal-timeline

**Comment by Gobinathsekar** [comment]
@luisjf  same issue faced

**Comment by claudia-romano** [comment]
Hi there, sorry for getting back after quite some time.
We have just released a new version (2.0) of this experiment (based on the [CodyHouse framework](https://codyhouse.co/ds/docs/framework)).

With this new version, you can initialize the timeline at a later time (once your content has been loaded). You can find more details in the [experiment article](https://codyhouse.co/gem/horizontal-timeline).
