### ISSUE TITLE
icons and folding panels

### ISSUE THREAD

**Issue by weedkiller** [CodyHouse/horizontal-timeline#4]
Hi when I try to put a bootstrap div with icons inside and js 3 the timeline does not scroll

**Comment by claudia-romano** [comment]
Hi there, sorry for getting back quite late. 

We do not provide fixes for custom style. 
If you can recreate the bug adding some content without importing additional custom style, feel free to post it and we'll try to fix the issue.

In the meantime, I'll close this issue.
