### ISSUE TITLE
not able to use in angularjs, Will you please provide me the directive of this

### ISSUE THREAD

**Issue by 28pankaj** [CodyHouse/horizontal-timeline#6]
not able to use in angular js, Will you please provide me the directive of this

**Comment by JongSikLim** [comment]
I'm using this with angular.js well. But One date (li>a) element need in html.

**Comment by claudia-romano** [comment]
Hi there, unfortunately we do not provide angular.js version of our experiments.

I'm closing this as this won't be implemented.
