### ISSUE TITLE
Changing the order of timeline

### ISSUE THREAD

**Issue by Pankesh88** [CodyHouse/horizontal-timeline#8]
Currently the most recent event is on left, Can we make it configurable for right side.

**Comment by sebastiano-guerriero** [comment]
hi there! sure, it's definitely possible. Unfortunately, we can't help with the customization of the resource. I can't count this as an "issue", so I'm gonna have to close the issue here on GitHub.

**Comment by nelsonamaya82** [comment]
Hi, I know it's not an issue, but I tried to change the timeline order and couldn't achieve it, could you give me some inputs on how this can be done?  Thanks!
