### ISSUE TITLE
Timeline starts in the middle of the line - desparately need help!

### ISSUE THREAD

**Issue by donnakat1** [CodyHouse/horizontal-timeline#9]
I am brand new to javascript and just cannot figure this out. The timeline starts 200px into the line and when it displays on mobile there is barely the first date. I cannot see how this calculation is being made and I need to fix it immediately. The site is to go live monday. Any help would be greatly appreciated. The only change I have made to the original script is: eventsMinDistance =120;

The page it is displayed is here. http://acpsales-4218991.hs-sites.com/company

Thank you

**Comment by claudia-romano** [comment]
Hi there, sorry for getting back after quite some time.
I'm closing this as it seems you have fixed this issue. Cheers!
